# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Eric Chen
url:              http://ericjwdchen.org
paginate:         5
baseurl:          /
author:
  name:           Eric Chen
  url:            https://twitter.com/ericjwdchen_org
  email:          eric@ericjwdchen.org

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ericjwdchen/ericjwdchen.github.io

gems:
  - jekyll-sitemap

sass:
  style: :compressed
