# Dependencies
markdown: kramdown
pygments: true

# Markdown settings
 Kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false


# Permalinks
permalink:        pretty

# Setup
title:            Eric Chen
tagline:          a high-functioning nerd
url:              http://ericjwdchen.github.io
paginate:         5
baseurl:          /
author:	
  name:           Eric Chen
  url:            https://twitter.com/ericjwdchen
  email:          eric.jwd.chen@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ericjwdchen/ericjwdchen.github.io
